name: afyadz
description: Afya DZ Doctor AI App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  http: ^1.2.0
  webview_flutter: ^4.8.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  introduction_screen: ^3.1.14
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # ðŸ‘‡ Ø§Ù„ØªØ¹Ø¯ÙŠÙ„ Ù‡Ù†Ø§: Ø­Ø°ÙÙ†Ø§ Ø§Ø³Ù… Ø§Ù„Ù…Ø¬Ù„Ø¯ Ù„Ø£Ù† Ø§Ù„ØµÙˆØ±Ø© ÙÙŠ Ø§Ù„Ø®Ø§Ø±Ø¬
  assets:
    - logo.png
