name: afyadz
description: Afya DZ Doctor AI App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  # ðŸ‘‡ Ø­Ø°ÙÙ†Ø§ Ù…ÙƒØªØ¨Ø© Ø¬ÙˆØ¬Ù„ ÙˆØ£Ø¶ÙÙ†Ø§ Ù…ÙƒØªØ¨Ø© Ø§Ù„Ø§ØªØµØ§Ù„ Ø§Ù„Ø¹Ø§Ù…
  http: ^1.2.0
  webview_flutter: ^4.8.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
